# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
    [
        {
            "name": "tag41_12_bundle_00000-11x11",
            "layout": [
                {
                    "id": 0,
                    "size": 0.18,
                    "x": -1.09,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 1,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 2,
                    "size": 0.18,
                    "x": -0.29,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 3,
                    "size": 0.18,
                    "x": 0.11,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 4,
                    "size": 0.18,
                    "x": 0.51,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 5,
                    "size": 0.18,
                    "x": 0.91,
                    "y": -1.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 6,
                    "size": 0.18,
                    "x": -0.89,
                    "y": -0.89,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 7,
                    "size": 0.18,
                    "x": -0.49,
                    "y": -0.89,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 8,
                    "size": 0.18,
                    "x": -0.09,
                    "y": -0.89,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 9,
                    "size": 0.18,
                    "x": 0.31,
                    "y": -0.89,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 10,
                    "size": 0.18,
                    "x": 0.71,
                    "y": -0.89,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 11,
                    "size": 0.18,
                    "x": -1.09,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 12,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 13,
                    "size": 0.18,
                    "x": -0.29,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 14,
                    "size": 0.18,
                    "x": 0.11,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 15,
                    "size": 0.18,
                    "x": 0.51,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 16,
                    "size": 0.18,
                    "x": 0.91,
                    "y": -0.6900000000000001,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 17,
                    "size": 0.18,
                    "x": -0.89,
                    "y": -0.49,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 18,
                    "size": 0.18,
                    "x": -0.49,
                    "y": -0.49,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 19,
                    "size": 0.18,
                    "x": -0.09,
                    "y": -0.49,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 20,
                    "size": 0.18,
                    "x": 0.31,
                    "y": -0.49,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 21,
                    "size": 0.18,
                    "x": 0.71,
                    "y": -0.49,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 22,
                    "size": 0.18,
                    "x": -1.09,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 23,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 24,
                    "size": 0.18,
                    "x": -0.29,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 25,
                    "size": 0.18,
                    "x": 0.11,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 26,
                    "size": 0.18,
                    "x": 0.51,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 27,
                    "size": 0.18,
                    "x": 0.91,
                    "y": -0.29,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 28,
                    "size": 0.18,
                    "x": -0.89,
                    "y": -0.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 29,
                    "size": 0.18,
                    "x": -0.49,
                    "y": -0.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 30,
                    "size": 0.18,
                    "x": -0.09,
                    "y": -0.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 31,
                    "size": 0.18,
                    "x": 0.31,
                    "y": -0.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 32,
                    "size": 0.18,
                    "x": 0.71,
                    "y": -0.09,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 33,
                    "size": 0.18,
                    "x": -1.09,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 34,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 35,
                    "size": 0.18,
                    "x": -0.29,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 36,
                    "size": 0.18,
                    "x": 0.11,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 37,
                    "size": 0.18,
                    "x": 0.51,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 38,
                    "size": 0.18,
                    "x": 0.91,
                    "y": 0.11,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 39,
                    "size": 0.18,
                    "x": -0.89,
                    "y": 0.31,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 40,
                    "size": 0.18,
                    "x": -0.49,
                    "y": 0.31,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 41,
                    "size": 0.18,
                    "x": -0.09,
                    "y": 0.31,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 42,
                    "size": 0.18,
                    "x": 0.31,
                    "y": 0.31,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 43,
                    "size": 0.18,
                    "x": 0.71,
                    "y": 0.31,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 44,
                    "size": 0.18,
                    "x": -1.09,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 45,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 46,
                    "size": 0.18,
                    "x": -0.29,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 47,
                    "size": 0.18,
                    "x": 0.11,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 48,
                    "size": 0.18,
                    "x": 0.51,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 49,
                    "size": 0.18,
                    "x": 0.91,
                    "y": 0.51,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 50,
                    "size": 0.18,
                    "x": -0.89,
                    "y": 0.71,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 51,
                    "size": 0.18,
                    "x": -0.49,
                    "y": 0.71,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 52,
                    "size": 0.18,
                    "x": -0.09,
                    "y": 0.71,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 53,
                    "size": 0.18,
                    "x": 0.31,
                    "y": 0.71,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 54,
                    "size": 0.18,
                    "x": 0.71,
                    "y": 0.71,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 55,
                    "size": 0.18,
                    "x": -1.09,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 56,
                    "size": 0.18,
                    "x": -0.6900000000000001,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 57,
                    "size": 0.18,
                    "x": -0.29,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 58,
                    "size": 0.18,
                    "x": 0.11,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 59,
                    "size": 0.18,
                    "x": 0.51,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                },
                {
                    "id": 60,
                    "size": 0.18,
                    "x": 0.91,
                    "y": 0.91,
                    "qw": 1,
                    "qx": 0,
                    "qy": 0,
                    "qz": 0
                }
            ]
        }
    ]